BEGIN;

CREATE TABLE IF NOT EXISTS funds (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL UNIQUE,
	category TEXT NOT NULL DEFAULT 'uncategorized'
);

CREATE TABLE IF NOT EXISTS transactions (
	id TEXT PRIMARY KEY,
	"date" DATE NOT NULL,
	merchant TEXT NOT NULL,
	canonical_merchant TEXT NOT NULL DEFAULT 'uncategorized',
	category TEXT NOT NULL DEFAULT 'uncategorized',
	amount NUMERIC(18,2) NOT NULL,
	currency CHAR(3) NOT NULL,
	memo TEXT,
	CHECK (char_length(currency) = 3)
);

CREATE TABLE IF NOT EXISTS fund_nav (
	fund_id TEXT NOT NULL REFERENCES funds(id) ON DELETE CASCADE,
	"date" DATE NOT NULL,
	nav NUMERIC(20,6) NOT NULL,
	PRIMARY KEY (fund_id, "date"),
	CHECK (nav > 0)
);

CREATE TABLE IF NOT EXISTS holdings (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	fund_id TEXT NOT NULL REFERENCES funds(id) ON DELETE CASCADE,
	fund_name TEXT NOT NULL,
	units NUMERIC(20,6) NOT NULL,
	purchase_date DATE NOT NULL,
	purchase_nav NUMERIC(20,6) NOT NULL,
	CHECK (units > 0),
	CHECK (purchase_nav > 0)
);

CREATE INDEX IF NOT EXISTS idx_transactions_date ON transactions ("date");
CREATE INDEX IF NOT EXISTS idx_transactions_category ON transactions (category);
CREATE INDEX IF NOT EXISTS idx_transactions_canonical_merchant ON transactions (canonical_merchant);

COMMIT;